language: node_js
node_js:
  - "4"
services:
  - mongodb
script:
  - npm run db
  - npm run test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8