language: node_js
node_js:
  - "4"
services:
  - mongodb
before_script:
  - curl -X PUT mongodb://localhost/worklyES6
script:
  - npm run db
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8