language: node_js
node_js:
- '4'
services:
- mongodb
script:
- npm run db
- npm run test
deploy:
  provider: heroku
  app: workly
  api_key:
    secure: D7OTzJF6fcP/5XD7MwqvwQeIOFanJzZixIJOaMFKwG2Rl2uuFfx0LCmA35I+ikuzodBcMecvjUo0U4dSyGhUwRWIvNYQGsAhaonzaS1nFcfN6yz1rmbrAhBRmcE6TPL8wzFEUxeDQltzOkWg3dl6dNJA1I0Bx/edcyBvQh0u4ZheyBcnpCJJVMMeXJW1v3SD4Hrc0DfybMlR5aPUqzF8j1F7UnpjSkYMsTEOzAugphfoyGl6BTArxBTfradDAyeYzeiWWZqJzLfdjk8dwnsXgSTojCeJe3bKaaF72H/HFxtm3bJ0J8T0M4LQTnKtuL9eveh9+SUIFNcEUZKL76tUYfFZa64jhknk2y0j9kWg0mmw4xIvsOUdcGNyXagxmBgUrAhXhlyvHFINsXRZJO1/B8yY45Yfv5zWUnVQmsZEmoLWeDUcQ0469iQ/kcXto2hzqQtzV2PDclXBz/Tujs4sxORnyQgGzBOiSE/FUDgGimzEUTFwR+LvwFSrnZhqcaPdfHfOtZUfw5sUfnTgRuA61fiAgAcqzn67p9CjyJWMr7T9kcCzqGgDF6/kKzquhvI3yynSpegUAiGCz4SU6ad77Q0MnYjX+k4WnTFcJ79KFLz0kuZCnvMrO8J0YRXxbiOwM7uVh5csGCZUhdgMy4OEPLGcH63+NpP9Mwp+BeHklkU=
  on: master
#after_deploy:
#  - npm run test_prod
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
