language: node_js
node_js:
- '4'
services:
- mongodb
script:
- npm run db
- npm run test
deploy:
  provider: heroku
  app: workly
  api_key:
    secure: $HEROKU_KEY
  on: master
after_deploy:
  - npm run test_prod
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
