language: node_js
node_js:
  - "4"
services:
  - mongodb
script:
  - npm run db
  - npm run test
deploy:
  provider: heroku
  api_key: 40952476-72da-4dfe-9309-86749989faa7
  app: workly
  on:
    	branch: master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8